apiVersion: batch/v1
kind: Job
metadata:
  name: complex-nn-job-gpu
spec:
  template:
    spec:
      imagePullSecrets:
        - name: nvcr.dgxkey
      containers:
        - name: complex-nn-container
          image: pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime  # CUDA-enabled PyTorch image
          command: ["bash", "-c"]
          args:
            - |
              set -e
              echo "=== Complex Neural Network Job Started ==="
              echo "Python version: $(python --version)"
              echo "Current time: $(date)"
              
              # Verify CUDA is available
              echo "=== Checking CUDA availability ==="
              nvidia-smi
              python -c "import torch; print(f'CUDA available: {torch.cuda.is_available()}'); print(f'Number of GPUs: {torch.cuda.device_count()}')"

              # Install system dependencies
              echo "=== Installing system dependencies ==="
              apt-get update && apt-get install -y git

              # Clone the repository
              echo "=== Cloning repository ==="
              git clone https://github.com/Snehgal/ComplexNeuralNetworks.git
              cd ComplexNeuralNetworks

              # List contents to verify
              echo "=== Repository contents ==="
              ls -la
              ls -la Concept/ 2>/dev/null || echo "Concept directory not found"

              # Install requirements
              echo "=== Installing Python requirements ==="
              if [ -f "requirements.txt" ]; then
                  cat requirements.txt
                  pip install --no-cache-dir -r requirements.txt
              else
                  echo "requirements.txt not found, installing common dependencies"
                  pip install --no-cache-dir numpy matplotlib scipy scikit-learn
              fi

              # Install torchsummary
              pip install --no-cache-dir torchsummary

              # Run the main script
              echo "=== Starting main script ==="
              if [ -f "Concept/main.py" ]; then
                  python -u Concept/main.py
              else
                  echo "main.py not found, listing available Python files:"
                  find . -name "*.py" -type f
              fi

              echo "=== Job completed successfully at $(date) ==="
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
              nvidia.com/gpu: 1  # Requesting 1 GPU
      restartPolicy: Never
  backoffLimit: 3
