apiVersion: apps/v1
kind: Deployment
metadata:
  name: mhapod-new  # Change deployment name
spec:
  selector:
    matchLabels:
      run: pytorch-new  # Change label selector
  replicas: 1
  template:
    metadata:
      labels:
        run: pytorch-new  # Change pod label
    spec:
      containers:
        - name: pytorch
          image: nvcr.io/nvidia/pytorch:24.05-py3
          command: ["/bin/sh", "-c"]
          args:
            - >
              jupyter lab --allow-root --ip=0.0.0.0 --NotebookApp.token='iiitd@123'
          resources:
            limits:
              nvidia.com/gpu: 1
              memory: 16Gi
            requests:
              memory: 8Gi
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: pytorch-data
              mountPath: /workspace
            - name: dshm
              mountPath: /dev/shm
          workingDir: /workspace
      volumes:
        - name: pytorch-data
          hostPath:
            path: /scratch/home/chirag23176  # Same base path
            type: Directory
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 4Gi