apiVersion: v1
kind: Service
metadata:
  name: pytorch-service-2
spec:
  selector:
    run: pytorch-new 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
      nodePort: 30011
  type: NodePort